title: "Dr. NANDINI YADAV"
email: "nandini7754@gmail.com"
description: "Plasma physicist"
baseurl: ""
url: "https://researcher.github.io"
#url: "http://localhost:4000"
theme: minima
plugins:
  - jekyll-feed
include:
  - pages
