title: "Dr. NANDINI YADAV"
email: "nandini7754@gmail.com"
description: "Plasma physicist"
baseurl: "/Researcher-NandiniYadav"
url: "https://srv22.github.io"
#url: "http://localhost:4000"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
include:
  - pages

# Set the default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "pages/about.md"
    values:
      permalink: /
